import type { Metadata, Viewport } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { Providers } from '@/components/providers';
import { ServiceWorkerRegistration } from '@/components/service-worker-registration';
import { SITE_DESCRIPTION, SITE_NAME, SITE_TITLE, SITE_URL } from '@/src/lib/site';

// Inter — variable font covering weights 100–900 and optical sizes
// font-display: swap ensures text is always visible during font load
const inter = localFont({
  src: [
    {
      path: '../public/fonts/Inter/Inter-VariableFont_opsz,wght.ttf',
      style: 'normal',
    },
    {
      path: '../public/fonts/Inter/Inter-Italic-VariableFont_opsz,wght.ttf',
      style: 'italic',
    },
  ],
  variable: '--font-inter-variable',
  display: 'swap',
  fallback: ['Segoe UI', 'Arial', 'sans-serif'],
});

// Scheherazade New — purpose-built for Quranic Arabic
// Uses Quranic-subsetted woff2 files (generated by `npm run subset-fonts`).
// font-display: optional prevents layout shift on first load;
// correct font loads from cache on every subsequent visit (including offline).
const scheherazadeNew = localFont({
  src: [
    {
      path: '../public/fonts/Scheherazade_New/ScheherazadeNew-Regular-quran-subset.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Scheherazade_New/ScheherazadeNew-Medium-quran-subset.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/Scheherazade_New/ScheherazadeNew-SemiBold-quran-subset.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/Scheherazade_New/ScheherazadeNew-Bold-quran-subset.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-scheherazade-variable',
  display: 'optional',
  fallback: ['Amiri', 'serif'],
});

export const metadata: Metadata = {
  // Resolves the relative OpenGraph and canonical URLs below. Driven by NEXT_PUBLIC_SITE_URL
  // because the production domain is still a placeholder across the docs.
  metadataBase: new URL(SITE_URL),
  title: {
    default: SITE_TITLE,
    template: `%s | ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  manifest: '/manifest.json',
  alternates: { canonical: '/' },
  icons: {
    icon: [
      { url: '/favicon.svg', type: 'image/svg+xml' },
      { url: '/favicon.ico', sizes: 'any' },
    ],
    apple: [{ url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' }],
    shortcut: '/favicon.ico',
  },
  openGraph: {
    type: 'website',
    siteName: SITE_NAME,
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    url: '/',
    images: [{ url: '/og-card.png', width: 1200, height: 630, alt: SITE_TITLE }],
  },
  twitter: {
    card: 'summary_large_image',
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    images: ['/og-card.png'],
  },
};

export const viewport: Viewport = {
  // Matches theme_color in public/manifest.json.
  themeColor: '#2f6f5c',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      dir="ltr"
      className={`${inter.variable} ${scheherazadeNew.variable}`}
      suppressHydrationWarning
    >
      <body>
        <Providers>{children}</Providers>
        <ServiceWorkerRegistration />
      </body>
    </html>
  );
}
